In [3]:
import numpy as np

X=np.array(([2,9],[1,5],[3,6]))
y=np.array(([92],[86],[89]))
y=y/100

def sigmoid(x):
    return 1/(1+np.exp(-x))

def der_sig(x):
    return x*(1-x)

epoch=10000
lr=0.1
iln=2
hln=3
oln=1

wh=np.random.uniform(size=(iln,hln))
bh=np.random.uniform(size=(1,hln))
wout=np.random.uniform(size=(hln,oln))
bout=np.random.uniform(size=(1,oln))

for i in range(epoch):
    hinp1=np.dot(X,wh)
    hinp=hinp1+bh
    hla=sigmoid(hinp)
    
    outinp1=np.dot(hla,wout)
    outinp=outinp1+bout
    output=sigmoid(outinp)
    
    EO=y-output
    outgrad=der_sig(output)
    d_output=EO*outgrad
    
    EH=d_output.dot(wout.T)
    hiddengrad=der_sig(hla)
    d_hidden=EH*hiddengrad
    
    wout+=hla.T.dot(d_output)*lr
    wh+=X.T.dot(d_hidden)*lr
    bout+=np.sum(d_output,axis=0,keepdims=True)*lr
    bh+=np.sum(d_hidden,axis=0,keepdims=True)*lr
    
print("Input \n" + str(X))
print("Actual Output \n"+str(y))
print("Predicted Output \n",output)

Input 
[[2 9]
 [1 5]
 [3 6]]
Actual Output 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output 
 [[0.89466073]
 [0.87976441]
 [0.89388849]]
